### ISSUE TITLE
Blank Login-Page

### ISSUE THREAD

**Issue by devpumk** [housamz/php-mysql-admin-panel-generator#2]
Hi

After generating the admin-pages and trying to log in with admin/admin, the login.php page stays blank and nothing happens. Tried in several browsers. 
Any ideas?
Thanks
Dev

**Comment by tej-kweku** [comment]
In my case, it was due to my system using `Php 7` whiles the project uses `mysql` functions that were deprecated in `Php 7*`. You would realize that there would be an error in the console of the browser being used. Often it would be something like this:
`Failed to load resource: the server responded with a status of 500 (Internal Server Error)`
